---
include:
  - board: eyelash_corne_left
    # shield: nice_view
    shield: oled_adapter_pro_micro_128x32
    #snippet: zmk-usb-logging
  - board: eyelash_corne_right
    # shield: nice_view
    shield: oled_adapter_pro_micro_128x32
    #snippet: zmk-usb-logging
  - board: eyelash_corne_left
    # shield: nice_view
    shield: nice_oled
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_corne_studio_left
  - board: eyelash_corne_left
    shield: settings_reset
    #snippet: zmk-usb-logging
 
